spring.datasource.url=jdbc:postgresql://postgres:5432/dotohtwo
spring.datasource.username=postgres
spring.datasource.password=password

spring.kafka.bootstrap-servers=kafka:9092

frontend.url=http://localhost:3000
