spring.datasource.url=jdbc:postgresql://localhost:5432/dotohtwodb
spring.datasource.username=postgres
spring.datasource.password=wish2514

spring.security.oauth2.client.registration.github.clientId=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.clientSecret=${GITHUB_CLIENT_SECRET}

frontend.url=http://localhost:3000/